Repository approval-please/approval-please-Spring, pull requests merged in 2023-01, with the labels that each got.

#20 Feature/#7 결재하기 게시글 등록 기능 구현
  src/main/java/com/umc/approval/domain/document/controller/DocumentController.java
  src/main/java/com/umc/approval/domain/document/dto/DocumentRequest.java
  src/main/java/com/umc/approval/domain/document/entity/DocumentRepository.java
  src/main/java/com/umc/approval/domain/document/service/DocumentService.java
  src/main/java/com/umc/approval/domain/image/entity/ImageRepository.java
  src/main/java/com/umc/approval/domain/image/service/ImageService.java
  src/main/java/com/umc/approval/domain/like_category/entity/LikeCategoryRepository.java
  src/main/java/com/umc/approval/domain/link/entity/LinkRepository.java
  src/main/java/com/umc/approval/domain/link/service/LinkService.java
  src/main/java/com/umc/approval/domain/tag/entity/TagRepository.java
  src/main/java/com/umc/approval/domain/tag/service/TagService.java
  src/main/java/com/umc/approval/domain/user/service/UserService.java
  src/main/java/com/umc/approval/global/security/filter/CustomAuthorizationFilter.java
Labels: 작업: feature, 도메인: 결재서류, 담당: 벨

#29 Feature/#28
  src/main/java/com/umc/approval/domain/user/controller/UserController.java
  src/main/java/com/umc/approval/domain/user/dto/UserDto.java
  src/main/java/com/umc/approval/domain/user/service/UserService.java
Labels: 작업: feature, 도메인: 로그인/회원가입, 담당: 샤피

#31 Feature/#27 카카오 로그인 구현
  src/main/java/com/umc/approval/domain/document/entity/DocumentRepository.java
  src/main/java/com/umc/approval/domain/user/controller/UserController.java
  src/main/java/com/umc/approval/domain/user/dto/UserDto.java
  src/main/java/com/umc/approval/domain/user/entity/UserRepository.java
  src/main/java/com/umc/approval/domain/user/service/UserService.java
  src/main/java/com/umc/approval/global/exception/CustomErrorType.java
  src/main/java/com/umc/approval/global/security/SecurityConfig.java
  src/main/java/com/umc/approval/global/security/dto/KakaoProfile.java
  src/main/java/com/umc/approval/global/security/exception/FirstSnsLoginException.java
  src/main/java/com/umc/approval/global/security/filter/CustomKakaoAuthenticationFilter.java
  src/main/java/com/umc/approval/global/security/handler/UserFailureHandler.java
  src/main/java/com/umc/approval/global/security/handler/UserSuccessHandler.java
  src/main/java/com/umc/approval/global/security/service/JwtService.java
  src/main/java/com/umc/approval/global/security/service/KakaoOAuth2Service.java
  src/test/java/com/umc/approval/unit/user/controller/UserControllerTest.java
  src/test/java/com/umc/approval/unit/user/service/UserServiceTest.java
Labels: 작업: feature, 도메인: 로그인/회원가입, 담당: 빠쿤

#37 Feature/#25 결재톡톡 게시글 수정 기능 구현
  src/main/java/com/umc/approval/domain/image/entity/Image.java
  src/main/java/com/umc/approval/domain/image/entity/ImageRepository.java
  src/main/java/com/umc/approval/domain/link/entity/LinkRepository.java
  src/main/java/com/umc/approval/domain/tag/entity/TagRepository.java
  src/main/java/com/umc/approval/domain/toktok/controller/ToktokController.java
  src/main/java/com/umc/approval/domain/toktok/dto/ToktokDto.java
  src/main/java/com/umc/approval/domain/toktok/entity/Toktok.java
  src/main/java/com/umc/approval/domain/toktok/service/ToktokService.java
  src/main/java/com/umc/approval/domain/vote/entity/Vote.java
  src/main/java/com/umc/approval/domain/vote/entity/VoteOption.java
  src/main/java/com/umc/approval/domain/vote/entity/VoteOptionRepository.java
  src/main/java/com/umc/approval/domain/vote/entity/VoteRepository.java
  src/main/java/com/umc/approval/global/exception/CustomErrorType.java
  src/main/java/com/umc/approval/global/security/filter/CustomAuthorizationFilter.java
Labels: 작업: feature, 도메인: 결재톡톡, 담당: 테사

#41 Feature/#39 댓글 등록 구현 (결재서류, 결재톡톡, 결재보고서 및 대댓글)
  src/main/java/com/umc/approval/domain/comment/controller/CommentController.java
  src/main/java/com/umc/approval/domain/comment/dto/CommentDto.java
  src/main/java/com/umc/approval/domain/comment/entity/CommentRepository.java
  src/main/java/com/umc/approval/domain/comment/service/CommentService.java
  src/main/java/com/umc/approval/domain/document/entity/Document.java
  src/main/java/com/umc/approval/domain/report/entity/Report.java
  src/main/java/com/umc/approval/domain/report/entity/ReportRepository.java
  src/main/java/com/umc/approval/domain/toktok/entity/Toktok.java
  src/main/java/com/umc/approval/domain/user/dto/UserDto.java
  src/main/java/com/umc/approval/global/exception/CustomErrorType.java
  src/main/java/com/umc/approval/global/security/filter/CustomAuthorizationFilter.java
  src/test/java/com/umc/approval/integration/comment/CommentServiceIntegrationTest.java
  src/test/java/com/umc/approval/integration/user/UserServiceIntegrationTest.java
  src/test/java/com/umc/approval/unit/comment/controller/CommentControllerTest.java
  src/test/java/com/umc/approval/unit/comment/service/CommentServiceTest.java
  src/test/resources/img/test.png
Labels: 작업: feature, 도메인: 공통, 담당: 빠쿤

#42 Feature/#33 결재하기 게시글 수정 기능 구현
  src/main/java/com/umc/approval/domain/document/controller/DocumentController.java
  src/main/java/com/umc/approval/domain/document/dto/DocumentDto.java
  src/main/java/com/umc/approval/domain/document/entity/Document.java
  src/main/java/com/umc/approval/domain/document/service/DocumentService.java
  src/main/java/com/umc/approval/global/security/filter/CustomAuthorizationFilter.java
Labels: 작업: feature, 도메인: 결재서류, 담당: 벨

#50 Feature/#44 결재보고서 게시글 등록 기능 구현
  src/main/java/com/umc/approval/domain/report/controller/ReportController.java
  src/main/java/com/umc/approval/domain/report/dto/ReportDto.java
  src/main/java/com/umc/approval/domain/report/entity/ReportRepository.java
  src/main/java/com/umc/approval/domain/report/service/ReportService.java
  src/main/java/com/umc/approval/domain/toktok/service/ToktokService.java
  src/main/java/com/umc/approval/global/exception/CustomErrorType.java
  src/main/java/com/umc/approval/global/security/filter/CustomAuthorizationFilter.java
Labels: 작업: feature, 도메인: 결재보고서, 담당: 테사

#61 Feature/#11 마이페이지 - 사원증 조회 (작성한 결재서류 = 전체 + 상태별 + 승인별)
  build.gradle
  src/main/java/com/umc/approval/domain/document/controller/DocumentController.java
  src/main/java/com/umc/approval/domain/document/dto/DocumentDto.java
  src/main/java/com/umc/approval/domain/document/entity/DocumentRepository.java
  src/main/java/com/umc/approval/domain/document/service/DocumentService.java
  src/main/java/com/umc/approval/domain/profile/controller/ProfileController.java
  src/main/java/com/umc/approval/domain/profile/service/ProfileService.java
  src/main/java/com/umc/approval/global/security/filter/CustomAuthorizationFilter.java
Labels: 작업: feature, 도메인: 결재서류, 담당: 원

#67 [FIX #64] 코드 충돌로 인한 빌드 실패 수정
  src/main/java/com/umc/approval/domain/document/dto/DocumentDto.java
  src/main/java/com/umc/approval/domain/document/service/DocumentService.java
  src/main/java/com/umc/approval/domain/follow/entity/FollowRepository.java
  src/main/java/com/umc/approval/domain/profile/service/ProfileService.java
Labels: 작업: fix, 도메인: 결재서류, 도메인: 사원증, 담당: 빠쿤

#81 [FIX #80] 마이페이지 - 사원증 프로필 수정
  src/main/java/com/umc/approval/domain/follow/entity/FollowRepository.java
  src/main/java/com/umc/approval/domain/like/service/LikeService.java
  src/main/java/com/umc/approval/domain/profile/service/ProfileService.java
Labels: 작업: fix, 도메인: 사원증, 담당: 원

#84 [FEATURE #72] 마이페이지 - 팔로워/팔로잉 목록 조회
  src/main/java/com/umc/approval/domain/profile/controller/ProfileController.java
  src/main/java/com/umc/approval/domain/profile/service/ProfileService.java
Labels: 작업: feature, 도메인: 사원증, 담당: 원

#83 [FEATURE #71] 마이페이지 - 실적 조회 (+사원증 프로필 조회 API)
  src/main/java/com/umc/approval/domain/performance/entity/PerformanceRepository.java
  src/main/java/com/umc/approval/domain/profile/controller/ProfileController.java
  src/main/java/com/umc/approval/domain/profile/service/ProfileService.java
  src/main/java/com/umc/approval/global/exception/CustomErrorType.java
  src/main/java/com/umc/approval/global/security/filter/CustomAuthorizationFilter.java
Labels: 작업: feature, 도메인: 사원증, 담당: 원

#101 Feature/#91 결재보고서 게시글 삭제 기능 구현
  src/main/generated/com/umc/approval/domain/QBaseTimeEntity.java
  src/main/generated/com/umc/approval/domain/accuse/entity/QAccuse.java
  src/main/generated/com/umc/approval/domain/approval/entity/QApproval.java
  src/main/generated/com/umc/approval/domain/cert/entity/QCert.java
  src/main/generated/com/umc/approval/domain/comment/entity/QComment.java
  src/main/generated/com/umc/approval/domain/document/entity/QDocument.java
  src/main/generated/com/umc/approval/domain/follow/entity/QFollow.java
  src/main/generated/com/umc/approval/domain/image/entity/QImage.java
  src/main/generated/com/umc/approval/domain/like/entity/QLike.java
  src/main/generated/com/umc/approval/domain/like_category/entity/QLikeCategory.java
  src/main/generated/com/umc/approval/domain/link/entity/QLink.java
  src/main/generated/com/umc/approval/domain/performance/entity/QPerformance.java
  src/main/generated/com/umc/approval/domain/report/entity/QReport.java
  src/main/generated/com/umc/approval/domain/scrap/entity/QScrap.java
  src/main/generated/com/umc/approval/domain/tag/entity/QTag.java
  src/main/generated/com/umc/approval/domain/toktok/entity/QToktok.java
  src/main/generated/com/umc/approval/domain/user/entity/QUser.java
  src/main/generated/com/umc/approval/domain/vote/entity/QUserVote.java
  src/main/generated/com/umc/approval/domain/vote/entity/QVote.java
  src/main/generated/com/umc/approval/domain/vote/entity/QVoteOption.java
  src/main/java/com/umc/approval/domain/comment/entity/CommentRepository.java
  src/main/java/com/umc/approval/domain/document/controller/DocumentController.java
  src/main/java/com/umc/approval/domain/like/entity/LikeRepository.java
  src/main/java/com/umc/approval/domain/report/controller/ReportController.java
  src/main/java/com/umc/approval/domain/report/service/ReportService.java
  src/main/java/com/umc/approval/domain/scrap/entity/ScrapRepository.java
  src/main/java/com/umc/approval/domain/toktok/service/ToktokService.java
  src/main/java/com/umc/approval/domain/vote/entity/UserVoteRepository.java
Labels: 작업: feature, 도메인: 결재보고서, 담당: 테사

#107 Feature/#106 댓글 목록 조회 페이징 기능 제거
  src/main/java/com/umc/approval/domain/comment/controller/CommentController.java
  src/main/java/com/umc/approval/domain/comment/dto/CommentDto.java
  src/main/java/com/umc/approval/domain/comment/entity/CommentRepositoryCustom.java
  src/main/java/com/umc/approval/domain/comment/entity/CommentRepositoryImpl.java
  src/main/java/com/umc/approval/domain/comment/service/CommentService.java
Labels: 작업: refactor, 도메인: 공통, 담당: 빠쿤

#141 Feature/#136 결재톡톡 검색기능 GUI에 맞춰 수정
  src/main/java/com/umc/approval/domain/toktok/dto/ToktokDto.java
  src/main/java/com/umc/approval/domain/toktok/entity/Toktok.java
  src/main/java/com/umc/approval/domain/toktok/entity/ToktokRepositoryImpl.java
Labels: 작업: refactor, 도메인: 결재톡톡, 담당: 빠쿤

#144 Feature/#142 결재톡톡&결재보고서 게시글 상세조회 수정사항 반영
  src/main/java/com/umc/approval/domain/report/controller/ReportController.java
  src/main/java/com/umc/approval/domain/report/dto/ReportDto.java
  src/main/java/com/umc/approval/domain/report/service/ReportService.java
  src/main/java/com/umc/approval/domain/scrap/entity/ScrapRepository.java
  src/main/java/com/umc/approval/domain/toktok/dto/ToktokDto.java
  src/main/java/com/umc/approval/domain/toktok/service/ToktokService.java
Labels: 작업: fix, 도메인: 결재보고서, 도메인: 결재톡톡, 담당: 테사

#158 Feature/#85 마이페이지 - 커뮤니티 (결재톡톡, 결재보고서) 조회 + 댓글 / 스크랩 조회 (유형별 : 결재서류, 결재톡톡, 결재보고서)
  src/main/generated/querydsl/com/umc/approval/domain/QBaseTimeEntity.java
  src/main/generated/querydsl/com/umc/approval/domain/accuse/entity/QAccuse.java
  src/main/generated/querydsl/com/umc/approval/domain/approval/entity/QApproval.java
  src/main/generated/querydsl/com/umc/approval/domain/cert/entity/QCert.java
  src/main/generated/querydsl/com/umc/approval/domain/comment/entity/QComment.java
  src/main/generated/querydsl/com/umc/approval/domain/document/entity/QDocument.java
  src/main/generated/querydsl/com/umc/approval/domain/follow/entity/QFollow.java
  src/main/generated/querydsl/com/umc/approval/domain/image/entity/QImage.java
  src/main/generated/querydsl/com/umc/approval/domain/like/entity/QLike.java
  src/main/generated/querydsl/com/umc/approval/domain/like_category/entity/QLikeCategory.java
  src/main/generated/querydsl/com/umc/approval/domain/link/entity/QLink.java
  src/main/generated/querydsl/com/umc/approval/domain/performance/entity/QPerformance.java
  src/main/generated/querydsl/com/umc/approval/domain/report/entity/QReport.java
  src/main/generated/querydsl/com/umc/approval/domain/scrap/entity/QScrap.java
  src/main/generated/querydsl/com/umc/approval/domain/tag/entity/QTag.java
  src/main/generated/querydsl/com/umc/approval/domain/toktok/entity/QToktok.java
  src/main/generated/querydsl/com/umc/approval/domain/user/entity/QUser.java
  src/main/generated/querydsl/com/umc/approval/domain/vote/entity/QUserVote.java
  src/main/generated/querydsl/com/umc/approval/domain/vote/entity/QVote.java
  src/main/generated/querydsl/com/umc/approval/domain/vote/entity/QVoteOption.java
  src/main/java/com/umc/approval/domain/comment/entity/CommentRepository.java
  src/main/java/com/umc/approval/domain/document/entity/DocumentRepository.java
  src/main/java/com/umc/approval/domain/follow/dto/FollowDto.java
  src/main/java/com/umc/approval/domain/follow/entity/FollowRepository.java
  src/main/java/com/umc/approval/domain/performance/dto/PerformanceDto.java
  src/main/java/com/umc/approval/domain/profile/controller/ProfileController.java
  src/main/java/com/umc/approval/domain/profile/service/ProfileService.java
  src/main/java/com/umc/approval/domain/report/controller/ReportController.java
  src/main/java/com/umc/approval/domain/report/dto/ReportDto.java
  src/main/java/com/umc/approval/domain/report/entity/Report.java
  src/main/java/com/umc/approval/domain/report/entity/ReportRepository.java
  src/main/java/com/umc/approval/domain/report/entity/ReportRepositoryCustom.java
  src/main/java/com/umc/approval/domain/report/entity/ReportRepositoryImpl.java
  src/main/java/com/umc/approval/domain/report/service/ReportService.java
  src/main/java/com/umc/approval/domain/scrap/entity/ScrapRepository.java
  src/main/java/com/umc/approval/domain/toktok/entity/ToktokRepository.java
  src/main/java/com/umc/approval/global/exception/CustomErrorType.java
Labels: 작업: feature, 도메인: 사원증, 담당: 원

#162 Feature/#159 결재서류 전체 목록조회 구현
  src/main/java/com/umc/approval/domain/document/controller/DocumentController.java
  src/main/java/com/umc/approval/domain/document/entity/DocumentRepositoryCustom.java
  src/main/java/com/umc/approval/domain/document/entity/DocumentRepositoryImpl.java
  src/main/java/com/umc/approval/domain/document/service/DocumentService.java
Labels: 작업: feature, 도메인: 결재서류, 담당: 빠쿤

#163 Feature/#160 결재서류 관심 목록 조회 구현
  src/main/java/com/umc/approval/domain/document/controller/DocumentController.java
  src/main/java/com/umc/approval/domain/document/entity/DocumentRepositoryCustom.java
  src/main/java/com/umc/approval/domain/document/entity/DocumentRepositoryImpl.java
  src/main/java/com/umc/approval/domain/document/service/DocumentService.java
  src/main/java/com/umc/approval/domain/like_category/entity/LikeCategoryRepository.java
Labels: 작업: feature, 도메인: 결재서류, 담당: 빠쿤
